//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anonymizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anonymizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Anonymizer]
        ///GO
        ////****** Object:  StoredProcedure [dbo].[sp_SimpleAnonymizer]    Script Date: 2019. 01. 17. 10:35:57 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///if type_id(&apos;dbo.AnonymizerColumnAndValueList&apos;) is null
        ///	begin
        ///		create type dbo.AnonymizerColumnAndValueList
        ///		as table
        ///		(
        ///			column_name nvarchar(128),
        ///			column_value nvarchar(max)
        ///		);
        ///	end
        ///go
        ///
        ///if type_id(&apos;dbo.AnonymizerColumnList&apos;) is null
        ///	begin
        ///		create type dbo.dbo.AnonymizerColumnList
        ///		as table
        ///		(
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_types {
            get {
                return ResourceManager.GetString("Create_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Anonymizer]
        ///GO
        ////****** Object:  StoredProcedure [dbo].[sp_SimpleAnonymizer]    Script Date: 2019. 01. 17. 10:35:57 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///
        ///declare @db nvarchar(128), @schema nvarchar(128),@table_name nvarchar(128),@enable bit
        ///
        ///select @db = @db_value, @schema = @schema_value, @table_name = @table_value, @enable = @enable_value
        ///
        ///declare @sql_to_get_indexes nvarchar(MAX) = &apos;&apos;, 
        ///		@full_table_name nvarchar(500) = @db + &apos;.&apos; + @schema + &apos;.&apos; + @table_name,
        ///		@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enabledisable_non_PrkeyUniqueClust_indexes {
            get {
                return ResourceManager.GetString("enabledisable_non_PrkeyUniqueClust_indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Anonymizer]
        ///GO
        ////****** Object:  StoredProcedure [dbo].[sp_SimpleAnonymizer]    Script Date: 2019. 01. 17. 10:35:57 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///	declare @columns as dbo.AnonymizerColumnList 
        ///    declare @db as nvarchar(128), @schema as nvarchar(128), @table as nvarchar(128)
        ///
        ///	insert into @columns 
        ///	select column_name 
        ///	from @columns_table
        ///
        ///	select @db = @db_value, @schema = @schema_value, @table = @table_value
        ///	
        ///	declare @column_count int
        ///	select @column_c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Get_Column_Types {
            get {
                return ResourceManager.GetString("Get_Column_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Anonymizer]
        ///GO
        ////****** Object:  StoredProcedure [dbo].[sp_SimpleAnonymizer]    Script Date: 2019. 01. 17. 10:35:57 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///
        ///-- =============================================
        ///-- Author:		Mark Rusz
        ///-- Create date: 2019-01-15
        ///-- Description:	Scrambles the given columns and sets other given columns to a constant value for a table
        ///-- =============================================
        ///
        ///
        ///SET XACT_ABORT, NOCOUNT ON
        ///
        ///--Input parameters
        ///declare @db n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Scramble {
            get {
                return ResourceManager.GetString("Scramble", resourceCulture);
            }
        }
    }
}
